# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say_hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  say_bye:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say Bye"
          command: "echo Bye, World!"

# Start anchors
tag-filter: &tag-filter # Use this to mark a job to run on tag pushes. This is needed for the workflow level tag filters to work since it checks job level filters first.
  filters:
    tags:
      only: /.*/
default-branch-filter: &default-branch-filter
  filters:
    branch:
      only: main
# End anchors2

workflows:
  say-hello-workflow:
    when:
      matches:
        pattern: "/staging-abcc-[0-9-]+/"
        value: << pipeline.git.tag >>
    jobs:
      - say_bye:
         <<: *tag-filter
      - say_hello:
          requires:
            - say_bye
          <<: *tag-filter